### ISSUE TITLE
你这个速度和py版的比过吗

### ISSUE THREAD

**Issue by lycaste** [wustMeiming/XlogDecoder#1]

**Comment by wustMeiming** [comment]
没有进行速度对比过，因为项目的需求不在效率上，主要是python版本的程序在一些旧的服务器（依赖的openssl版本太低又不能升级）部署不成功。如果对速度有需求可以翻译成C代码，理论是应该会快一些。

**Comment by lycaste** [comment]
昨晚试了下，我发现我们这边xlog文件    byte[] _buffer = new byte[dis.available()];
读出来以后 很多负数(大于127的数x 直接就变成x-256的负数了)
然后执行
`       
int single_log_len = ByteBuffer.wrap(tmpbuffer, 0,2).order(ByteOrder.LITTLE_ENDIAN).getInt(); 
`
对应的py
`
  single_log_len = struct.unpack_from("H", buffer(tmpbuffer, 0, 2))[0]
`

直接抛出异常java.nio.BufferUnderflowException

**Comment by wustMeiming** [comment]
我们这边几百万个文件倒是没出现过这个问题.
1.byte的取值范围是-128到127这个没问题
2.在我提供的代码里面没有找到single_log_len这个变量，应该是没有实现这个分支
3.如果要找问题原因可能需要用python版本和java的代码进行对比调试
4.如果可以的话，希望能提供相关文件，我这边可以进行调试分析(wustdb@gmail.com)
