### ISSUE TITLE
java.util.zip.ZipException: invalid stored block lengths 运行报错

### ISSUE THREAD

**Issue by ZhuSky** [wustMeiming/XlogDecoder#2]
![image](https://user-images.githubusercontent.com/18596232/70027191-8bc2a880-15dc-11ea-912a-fbd186e36241.png)
我运行项目的时候，报错了，请教一下，这个怎么处理？

**Comment by ZhuSky** [comment]
![image](https://user-images.githubusercontent.com/18596232/70027283-c1679180-15dc-11ea-9d04-f70b66bf3291.png)

**Comment by wustMeiming** [comment]
你的xlog文件用官方提供的python脚本可以正常解析吗？怀疑有可能是文件本身格式不符合

**Comment by ZhuSky** [comment]
之前的文件确实有些问题，不过现在又有了新的问题。
麻烦您看一下，谢谢🙏
![image](https://user-images.githubusercontent.com/18596232/70110377-bb7bba00-1689-11ea-9756-c85caa2c78e9.png)

**Comment by wustMeiming** [comment]
看起来跟加密算法有关，可能没那么容易解决，如果需要帮看的话，可以提供下xlog文件，我这边有空的话，可以帮你调试一下！

**Comment by ZhuSky** [comment]
好的明白了，我这边加密文件，涉及到公司，所以不方便，多谢您了 @wustMeiming

**Comment by zhanlan123** [comment]
把ECDHUtils.java中的文件 ECPrivateKeySpec prvkey = new ECPrivateKeySpec(new BigInteger(data), params);改为： ECPrivateKeySpec prvkey = new ECPrivateKeySpec(new BigInteger(1, data), params);就可以了。就可以兼容新旧xlog。@ZhuSky
@wustMeiming

**Comment by zhanlan123** [comment]
借用你的项目做核心，做了一个UI版本。运维不想用命令行。
