### ISSUE TITLE
最近在尝试写一个mac端解密小程序，使用您的代码解密的时候打印了这些异常：

### ISSUE THREAD

**Issue by xixinewbie** [wustMeiming/XlogDecoder#3]
Task start...
log length:2013267976, end pos 2013267992 > len(buffer):233127
log length:2893545480, end pos 2893545497 > len(buffer):233127
log length:5470124, end pos 5470204 > len(buffer):233127
log length:21367, buffer[21447]:-20 != MAGIC_END
log length:83, buffer[164]:-43 != MAGIC_END
log length:528074, end pos 528247 > len(buffer):233127
log length:510656520, end pos 510656695 > len(buffer):233127
log length:2871538408, end pos 2871538588 > len(buffer):233127
log length:1770054745, end pos 1770054958 > len(buffer):233127
log length:3708689904, end pos 3708690109 > len(buffer):233127
log length:308762558, end pos 308762859 > len(buffer):233127
log length:506082328, end pos 506082643 > len(buffer):233127
log length:1145068089, end pos 1145068528 > len(buffer):233127
log length:2541889174, end pos 2541889678 > len(buffer):233127
log length:3539511827, end pos 3539512356 > len(buffer):233127
log length:4194553869, end pos 4194554366 > len(buffer):233127
log length:201907512, end pos 201908016 > len(buffer):233127
log length:3273726779, end pos 3273727350 > len(buffer):233127
log length:3971495943, end pos 3971496512 > len(buffer):233127
log length:1546352955, end pos 1546353589 > len(buffer):233127
log length:155464678, end pos 155465323 > len(buffer):233127
log length:703948908, end pos 703949561 > len(buffer):233127
log length:1651139270, end pos 1651140087 > len(buffer):233127

一开始使用解压后的.xlog文件去解密，但是行不通，然后直接去解密zip文件，然后就报上面的问题，貌似这个end pos远大于buffer的length

**Comment by xixinewbie** [comment]
如果使用解压后的xlog文件去解密，报以下异常：
Task start...
0:0
java.util.zip.ZipException: invalid code lengths set
	at java.base/java.util.zip.InflaterOutputStream.write(InflaterOutputStream.java:273)
	at java.base/java.io.FilterOutputStream.write(FilterOutputStream.java:108)
	at com.meizu.sysmonitor.CommonUtils.decompress(CommonUtils.java:143)
	at com.meizu.sysmonitor.XlogFileDecoder.DecodeBuffer(XlogFileDecoder.java:171)
	at com.meizu.sysmonitor.XlogFileDecoder.ParseFile(XlogFileDecoder.java:221)
	at com.zhaoyuntao.myjava.MyXLog$1$1.run(MyXLog.java:72)
	at java.base/java.lang.Thread.run(Thread.java:834)
Exception in thread "Thread-0" java.lang.NullPointerException
	at java.base/java.lang.String.<init>(String.java:614)
	at com.meizu.sysmonitor.XlogFileDecoder.DecodeBuffer(XlogFileDecoder.java:188)
	at com.meizu.sysmonitor.XlogFileDecoder.ParseFile(XlogFileDecoder.java:221)
	at com.zhaoyuntao.myjava.MyXLog$1$1.run(MyXLog.java:72)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by wustMeiming** [comment]
这个代码是可以解用官方xlog库和对应public key加密的日志，你可以先尝试用官方python代码解密是否正常

**Comment by xixinewbie** [comment]
我使用他们的py脚本是可以解密的，我看您这个代码有段时间没更新过了，与py脚本中的逻辑有些不同，会不会是官方的解密方式与代码的逻辑不一致了？

**Comment by wustMeiming** [comment]
把你xlog文件发一份我，等我有空调试看看

**Comment by xixinewbie** [comment]
方便留一个邮箱吗，我把日志发您

**Comment by wustMeiming** [comment]
> 方便留一个邮箱吗，我把日志发您

meiming2015@foxmail.com

源文件以及解密后文件都需要 方便对比

**Comment by xixinewbie** [comment]
发过去了

**Comment by wustMeiming** [comment]
> 发过去了

收到

**Comment by zhanlan123** [comment]
把ECDHUtils.java中的文件 ECPrivateKeySpec prvkey = new ECPrivateKeySpec(new BigInteger(data), params);改为： ECPrivateKeySpec prvkey = new ECPrivateKeySpec(new BigInteger(1, data), params);就可以了。就可以兼容新旧xlog。
@wustMeiming @Zhaoyuntao

**Comment by wustMeiming** [comment]
> 把ECDHUtils.java中的文件 ECPrivateKeySpec prvkey = new ECPrivateKeySpec(new BigInteger(data), params);改为： ECPrivateKeySpec prvkey = new ECPrivateKeySpec(new BigInteger(1, data), params);就可以了。就可以兼容新旧xlog。 @wustMeiming @Zhaoyuntao

[log_20211220.xlog.log](https://github.com/wustMeiming/XlogDecoder/files/9460300/log_20211220.xlog.log)
改了试了下，好像还是解不出来

**Comment by wustMeiming** [comment]
> 把ECDHUtils.java中的文件 ECPrivateKeySpec prvkey = new ECPrivateKeySpec(new BigInteger(data), params);改为： ECPrivateKeySpec prvkey = new ECPrivateKeySpec(new BigInteger(1, data), params);就可以了。就可以兼容新旧xlog。 @wustMeiming @Zhaoyuntao

亲测可以解密，已合入主线，非常感谢 @zhanlan123
